### PR TITLE
Feat/update to 0.7.0

### PR DESCRIPTION
**Pull request by oddgrd**
Hey! Just a quick PR to update the code for shuttle `0.6.0`. I tested locally that it works, but if you have time to take a quick look and see that I didn't mess it up that would be cool! Until `0.6.0` is released it won't work, but that should be released later today. We'll let you know. :smile:

### CODE REVIEW

**Comment by kaleidawave** [comment]
Looks good. Like the simplifications to the secrets API 👍 . Ah didn't realize I had left `main.rs` in there. With the new `Shuttle.toml`, wouldn't changing the project id from `weather-discord-bot` to `ci-weather-discord-bot` now break deployments as this repo's `SHUTTLE_DEPLOY_KEY` is only authenticated for the `weather-discord-bot` project? (Might have slipped in there 😆)

**Comment by oddgrd** [comment]
Good catch! I'll take that out, it was mainly for testing.

**Comment by kaleidawave** [comment]
Awesome will merge and see if it passes the CI deploy 🤞

**Comment by oddgrd** [comment]
Ah, it won't, we need to update the GH action as well.

**Comment by kaleidawave** [comment]
Hmm yes looks like it failed. Will have another look tomorrow into why https://github.com/kaleidawave/discord-weather-bot/actions/runs/3275585673/jobs/5390622403

**Comment by kaleidawave** [comment]
@oddgrd The deployment error was:
```
Error: 503 Service Unavailable
message: project not ready
```
Is that a error on my end, or a blip by the deployer?

Does the action need an update? It is installs the latest [cargo shuttle binary (0.7.0 in this case)](https://github.com/kaleidawave/discord-weather-bot/actions/runs/3275585673/jobs/5390622403#step:4:39)

**Comment by oddgrd** [comment]
To deploy a service now after 0.6.0, a project must first be created with `cargo project new`. This starts a deployer container in which the services will be deployed.  The action would need to be updated to incorporate this, I opened a ticket for it internally. 

A container with the same project name was created for each existing project when we migrated. So there is a `weather-discord-bot` project (container), but it's currently in an errored state and also out of date (since 0.7.0) which is the cause of the "project not ready" error. So it would need to be remade with `cargo shuttle project rm` and `cargo shuttle project new`, and then `cargo shuttle deploy` must be ran with the updated source code.

**Comment by kaleidawave** [comment]
Ah I saw there were new sub-commands, didn't realise how they affected project setup. So if I run the "remove project" and "new project" commands locally, will a rerun of the deploy action work? I don't think the action should need changing, just needs to be under the clause that the project has been registered / new before...?

**Comment by oddgrd** [comment]
I believe that should work, yeah.

**Comment by kaleidawave** [comment]
Yo sorry was busy yesterday. I reset the project and retried and it deployed 🎉 but the process failed because the discord bot token was not found 😢 Is it a problem on my end, or is there issues with secrets? Will have a look tomorrow and try deploying locally and will have a look at the other PR :)

**Comment by oddgrd** [comment]
No prob, sounds good! There was an issue with secrets yeah, Pieter merged a PR for it just now and I believe it will be released tonight actually.

**Pull request merged**
